import React,{useEffect,useRef,useState} from 'react';
import data from './data/home.json';
import {Img,asset,media,Footer,DOWNLOAD} from './shared';
import './home.css';
const clamp=n=>Math.max(0,Math.min(1,n));
function useScene(smooth=false){
 const ref=useRef(null);const[p,setP]=useState(0);
 useEffect(()=>{let frame=0,target=0,value=0,last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const tick=time=>{const dt=last?Math.min(64,time-last):16;last=time;value=smooth&&!reduced.matches?value+(target-value)*(1-Math.exp(-dt/85)):target;if(Math.abs(target-value)<.00005)value=target;setP(value);frame=value!==target?requestAnimationFrame(tick):0;if(!frame)last=0;};
 const update=()=>{if(!ref.current)return;const r=ref.current.getBoundingClientRect();target=clamp(-r.top/Math.max(1,r.height-innerHeight));if(!frame)frame=requestAnimationFrame(tick);};
 update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update);reduced.addEventListener('change',update);
 return()=>{cancelAnimationFrame(frame);removeEventListener('scroll',update);removeEventListener('resize',update);reduced.removeEventListener('change',update)};
 },[smooth]);return[ref,p];
}
const Rich=({text,...props})=><span {...props} dangerouslySetInnerHTML={{__html:text.replaceAll('<accent>','<em>').replaceAll('</accent>','</em>')}}/>;
const home='/pages/home/';
function Hero(){const[ref,p]=useScene();const[vPaused,setPaused]=useState(false);const video=useRef();return <section ref={ref} className="home-hero"><div className="scene-sticky"><div className="hero-film"><video ref={video} autoPlay muted loop playsInline poster={asset(home+'hero/love-your-wardrobe-hero-still.jpg')} src={asset('/videos/pages/home/hero/LoveYourWardrobe_Herovideo_60fps.mp4')}/></div><div className="hero-title"><h1>Meet <span>your</span> wardrobe.</h1><p><Rich text={data.hero.subtitle.replace('{count}',data.hero.subtitleCount)}/></p></div><button className="film-toggle" aria-label={vPaused?'Play video':'Pause video'} onClick={()=>{vPaused?video.current.play():video.current.pause();setPaused(!vPaused)}}>{vPaused?'▶':'Ⅱ'}</button><div className="glass-reviews" style={{opacity:clamp(p*3),transform:`translateY(${(1-p)*100}px)`}}><div>{data.glassCards.quote}<span className="wordmark">StyleIQ</span></div><div><b>✧</b><strong>{data.glassCards.ratingsScore}</strong><small>{data.glassCards.ratingsLabel}</small></div></div></div></section>}
const blend=(p,start,end)=>{const t=clamp((p-start)/(end-start));return t*t*(3-2*t)};
function Dark(){const[ref,p]=useScene(true);const pics=['woman','man','travel','blazer','shell','product/top'];const weights=[1-blend(p,.20,.25),blend(p,.25,.30)*(1-blend(p,.42,.47)),blend(p,.47,.52)];const lines=[data.scrollText.line1,data.scrollText.line2,data.scrollText.sectionFour];return <section ref={ref} className="dark-story"><div className="scene-sticky"><div className="dark-photo-cloud" aria-hidden="true">{pics.map((name,i)=><Img key={i} src={'/assets/styleiq/'+name+'.webp'} className={'dark-photo photo-'+i} style={{transform:`translate3d(0,${(p-.35)*(i%2?180:-180)}px,0) rotate(${i%2?8:-8}deg)`}}/>)}</div><h2 className="scene-line dark-lines">{lines.map((text,i)=><Rich key={text} text={text} aria-hidden={weights[i]<.5} style={{opacity:weights[i],transform:`translate3d(0,${(i===0?-1:1)*(1-weights[i])*24}px,0)`}}/>)}</h2></div></section>}
function Seen(){const[ref,p]=useScene();return <section ref={ref} className="seen-scene"><div className="scene-sticky"><h2 style={{transform:`translateX(${(p-.5)*-70}vw)`}}>They need to be <em>{p<.5?'seen.':'worn.'}</em></h2><Img src={home+'light-middle/seen-worn/dancing-skirt.jpg'} style={{width:`${22+p*30}vw`,transform:`translate(-50%,-50%) rotate(${10-p*16}deg)`}}/></div></section>}
function Own(){const[ref,p]=useScene(true);const pics=media('/light-middle/see-own/').sort((a,b)=>a.url.localeCompare(b.url));return <section ref={ref} className="own-scene"><div className="scene-sticky"><h2>StyleIQ helps you see what you <em>own.</em></h2><div className="orbit">{pics.map((im,i)=>{const a=(i*45+p*100)*Math.PI/180;return <Img key={im.url} src={im.src} style={{transform:`translate(-50%,-50%) translate3d(${Math.cos(a)*37}vw,${Math.sin(a)*60}svh,0) scale(${.75+.25*Math.sin(a)})`}}/>})}</div></div></section>}
function Notice(){const[ref,p]=useScene();const pics=media(p<.5?'/understand-style/outfit-selfies/':'/understand-style/items/').sort((a,b)=>a.url.localeCompare(b.url));return <section ref={ref} className="notice-scene"><div className="scene-sticky"><div className="notice-images">{pics.map((im,i)=><Img key={im.url} src={im.src} style={{left:`${[3,75,5,76,32,53,15,73][i]}%`,top:`${[-15,-12,53,51,-29,77,20,26][i]}%`,transform:`rotate(${i%2?12:-9}deg) translateY(${(p-.5)*130}px)`}}/>)}</div><h2><Rich text={p<.5?data.noticeYouLove.text1:data.noticeYouLove.text2}/></h2></div></section>}
const folders=['your-wardrobe','create-outfits','wear-more','style-that-feels','see-how','loved-by','from-inspiration'];
const primary=['wardrobe-screen.png','dress-me-screen.png','wardrobe-composition.png','canvas-screen.png','feed-card-selfie.png','Vogue.png','chrome-extension.png'];
function Stack(){const[ref,p]=useScene();return <section ref={ref} id="how-it-works" className="stack-scene"><div className="scene-sticky">{data.stackingCards.map((c,i)=>{const start=i/7,progress=clamp((p-start)*7);const visible=p>=start-.13;const imgs=media('/stacked-cards/'+folders[i]+'/');return <article key={c.title} className={`feature-card card-${i}`} style={{visibility:visible?'visible':'hidden',transform:`translateY(${i===0?0:(1-progress)*110}%) rotate(${(1-progress)*(i%2?-4:4)}deg)`,filter:p>(i+1)/7?'brightness(.85)':'none',zIndex:i}}><div className="feature-copy"><h2>{c.title}<em>{c.titleAccent}</em></h2><p>{c.description}</p>{i===6&&<a className="pill-button" href={DOWNLOAD}>Get the app ↗</a>}</div><div className={`feature-art art-${i}`}>{i===5?imgs.map(im=><Img key={im.url} src={im.src}/>):<><Img className="primary-art" src={home+'how-it-works/stacked-cards/'+folders[i]+'/'+primary[i]}/>{imgs.filter(im=>!im.url.endsWith(primary[i])).slice(0,5).map((im,j)=><Img key={im.url} className={`accent-art accent-${j}`} src={im.src}/>)}</>}</div></article>})}</div></section>}
function Stages(){const[ref,p]=useScene();const[manual,setManual]=useState(null);useEffect(()=>setManual(null),[p]);const active=manual??Math.min(2,Math.floor(p*3));const current=data.seeWearBuild.stages[active];const folder=['see','wear','build'][active];return <section ref={ref} className="stage-scene"><div className="scene-sticky stage-panel"><div className="stage-art">{media('/see-wear-build/'+folder+'/').map((im,i)=><Img key={im.url} src={im.src} className={'stage-piece piece-'+i}/>)}</div><div className="stage-copy"><div className="stage-tabs" role="tablist" aria-label="See Wear Build">{data.seeWearBuild.stages.map((s,i)=><button role="tab" aria-selected={active===i} key={s.active} onClick={()=>setManual(i)}>{s.active}</button>)}</div><h2>{current.title}</h2><p>{current.subtitle}</p></div></div></section>}
function Community(){return <section className="community" id="about"><div className="community-art">{media('/how-it-works/join/').map((im,i)=><Img key={im.url} src={im.src} style={{transform:`rotate(${i%2?8:-8}deg)`}}/>)}</div><div><h2><Rich text={data.joinMillions.heading.replace('{count}',data.joinMillions.headingCount)}/></h2><p>{data.joinMillions.body}</p><div className="community-chips">{data.joinMillions.chips.map(c=><span key={c}>{c}</span>)}</div></div></section>}
function AppFeatures(){const[active,setActive]=useState(0);const files=['closet','studio','calendar','packing'];return <section className="app-features" id="app-tour"><div className="phone-frame"><Img src={'/assets/styleiq/screens/'+files[active]+'.webp'} alt={'StyleIQ — '+data.appVideo.subsections[active].title}/></div><div className="phone-controls">{data.appVideo.subsections.map((s,i)=><div key={s.title} className={active===i?'active':''}><button aria-label={'Show '+s.title} aria-expanded={active===i} onClick={()=>setActive(i)}>{s.title}</button>{active===i&&<p>{s.description}</p>}</div>)}</div></section>}
function Testimonials(){const[index,setIndex]=useState(0);return <section className="testimonials" aria-label="Explore StyleIQ"><div className="testimonial-track">{[0,1,2].map(offset=>{const c=data.testimonials[(index+offset)%data.testimonials.length];return <article key={c.pill}><Img src={c.image} alt={c.pill}/><h3>{c.quote}</h3><p>{c.body}</p><span>{c.pill}</span></article>})}</div><div className="carousel-buttons"><button aria-label="Previous testimonials" onClick={()=>setIndex((index+data.testimonials.length-1)%data.testimonials.length)}>←</button><button aria-label="Next testimonials" onClick={()=>setIndex((index+1)%data.testimonials.length)}>→</button></div></section>}
export default function Home(){return <main className="home" id="top"><Hero/><Dark/><div className="light-story"><Seen/><Own/><Notice/><Stack/><Stages/><Community/><AppFeatures/></div><Testimonials/><Footer/></main>}
