import React,{useEffect,useRef,useState} from 'react';
import {Img,asset,Footer,CONTACT} from './shared';
import info from './data/info.json';
import './info.css';

// Motion is tied to viewport progress, so wheel/touch and reverse scrolling agree.
function ScrollScene({className,children}){const ref=useRef();useEffect(()=>{let frame;const update=()=>{frame=requestAnimationFrame(()=>{if(!ref.current)return;const r=ref.current.getBoundingClientRect();const p=Math.max(0,Math.min(1,-r.top/Math.max(1,r.height-window.innerHeight)));ref.current.style.setProperty('--progress',p);ref.current.style.setProperty('--visible',Math.max(0,Math.min(1,(window.innerHeight-r.top)/(window.innerHeight*.8))));})};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);return <section ref={ref} className={className}>{children}</section>}
function Reveal({children,className=''}){const ref=useRef();useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('entered',e.isIntersecting)),{threshold:.12});observer.observe(ref.current);return()=>observer.disconnect()},[]);return <div ref={ref} className={'info-reveal '+className}>{children}</div>}
const clothing=['blue-striped-shirt','brown-asymmetrical-top','pink-cutout-dress','red-sleeveless-blouse','white-collared-shirt','yellow-jersey'];
function AboutVideo(){const video=useRef();const [paused,setPaused]=useState(false);return <ScrollScene className="about-video-scene"><div className="about-video-sticky"><video ref={video} autoPlay loop muted playsInline poster={asset('/pages/home/hero/love-your-wardrobe-hero-still.jpg')} src={asset('/videos/pages/home/hero/LoveYourWardrobe_Herovideo_60fps.mp4')}/><button onClick={()=>{if(video.current.paused){video.current.play();setPaused(false)}else{video.current.pause();setPaused(true)}}} aria-label={paused?'Play video':'Pause video'}>{paused?'▶':'Ⅱ'}</button></div></ScrollScene>}
export function About(){return <main className="about-page"><section className="about-hero"><div className="about-clothes">{clothing.map((name,i)=><Img key={name} src={'/pages/about/top/'+name+'.png'} style={{'--i':i}} alt=""/>)}</div><h1>Where style <br/><em>feels</em> like you.</h1></section><AboutVideo/><section className="about-story"><div className="about-story-inner">{info.intro.map((p,i)=><Reveal className={'story-item story-item-'+i} key={p}><p>{p}</p></Reveal>)}<Reveal className="about-survey"><blockquote>“94% of users report feeling more confident in their wardrobe after using Whering.”</blockquote><span>Survey of 10,000+ users in 2025</span></Reveal></div></section><section className="about-manifesto" id="manifesto"><div className="manifesto-inner"><h2>Manifesto</h2>{info.manifesto.map(p=><Reveal key={p}><p>{p}</p></Reveal>)}</div></section><section className="about-founder"><div className="founder-canvas"><div className="founder-label">Why Whering exists</div><Reveal className="founder-quote-first"><h2>“In a world obsessed with what’s next,</h2></Reveal><ScrollScene className="founder-shutters">{[0,1,2,3].map(i=><div key={i}><Img src="/pages/about/founder/founder-in-dark.jpg" alt="Bianca Rangecroft"/></div>)}</ScrollScene><Reveal className="founder-quote-last"><h2>Whering is a return to what’s yours.”</h2></Reveal><Reveal className="founder-first-copy"><p>Bianca Rangecroft founded Whering to change the way we interact with our clothes.</p><p>She had a wardrobe full of clothes, but nothing to wear and getting dressed felt harder than it should.</p><p>She realised it wasn’t only her wardrobe, but a broken system. Without a clear view of what you own, it’s easy to think one more piece will fix it.</p></Reveal><Reveal className="founder-hanger"><Img src="/pages/about/founder/founder-holding-hanger.jpg" alt="Bianca Rangecroft"/></Reveal><Reveal className="founder-quote-dressed"><h2>“Getting dressed still felt harder than it should.”</h2></Reveal><Reveal className="founder-light"><Img src="/pages/about/founder/founder-in-light.jpg" alt="Bianca Rangecroft"/></Reveal><Reveal className="founder-last-copy"><p>So she built Whering, redefining not just her wardrobe, but how millions of people get dressed.</p><p>Helping people see what they own and find what works for them, on their own terms.</p><p>Bianca founded Whering in 2020.</p><p>Today, it’s used by over 10 million people globally.</p></Reveal></div></section><section className="about-team"><h2>Meet the team</h2><ScrollScene className="team-photos">{['group-looking-away','group-moving','group-standing'].map(name=><Img key={name} src={'/pages/about/team/'+name+'.jpg'} alt="The Whering team"/>)}</ScrollScene><Reveal className="team-copy">{info.team.map(p=><p key={p}>{p}</p>)}<a className="pill" href={CONTACT}>Get in touch ↗</a></Reveal></section><Footer/></main>}
const careerImages=['back-of-person','bag-in-air','boots-in-tall-grass','person-holding-flowers','person-holding-rose','person-seated-heels','person-seated-shoes','person-wearing-hat','red-bow-on-blouse','two-people-holding-shoes'];
export function Careers(){return <main className="careers-page"><section className="careers-hero"><h1>Come build a better<br/>way to get dressed</h1><a className="careers-open" href="#open-roles">Open roles ↓</a><ScrollScene className="careers-images"><div>{careerImages.map((name,i)=><Img key={name} src={'/pages/careers/'+name+'.png'} alt="" style={{'--offset':[80,30,115,40,90,120,55,100,25,75][i]+'px'}}/>)}</div></ScrollScene></section><section className="careers-description"><div className="careers-columns">{info.careers.columns.map(col=><div key={col.heading}><h2>{col.heading}</h2>{col.paragraphs.map((html,i)=><div key={i} dangerouslySetInnerHTML={{__html:html}}/>)}</div>)}</div></section><section className="careers-roles" id="open-roles"><h2>Open roles</h2><div>{info.careers.roles.map(role=><a key={role.href} href={role.href}><div><h3>{role.title}</h3><span>Remote, UK</span></div><span className="role-more">See more ↗</span></a>)}</div></section><Footer/></main>}
export function Legal({route}){const page=info.legal[route]||info.legal['/privacy-policy'];return <main className="legal-page"><article><h1>{page.title}</h1><p className="legal-updated">{page.updated}</p><div className="legal-prose" dangerouslySetInnerHTML={{__html:page.html}}/></article></main>}
