import React, {useEffect,useState} from 'react';
import assets from './data/assets.json';
export const asset=(name)=>{const mapped=assets[name]||Object.entries(assets).find(([u])=>u.endsWith(name)||decodeURI(u).endsWith(name))?.[1]||name;return mapped.startsWith('/assets/')?(window.__ASSET_BASE__||'')+mapped:mapped};
export const media=(part)=>Object.entries(assets).filter(([u])=>u.includes(part)).sort(([a],[b])=>a.localeCompare(b)).map(([url,src])=>({url,src:asset(src)}));
export const DOWNLOAD='#get-the-app';
export const CONTACT='#get-the-app';
export const CHROME='#app-tour';
export function Img({src,alt='',...props}){return <img src={asset(src)} alt={alt} {...props}/>}
export function Header(){const[open,setOpen]=useState(false);useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>{document.body.style.overflow=''}},[open]);useEffect(()=>{const fn=e=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);const close=()=>setOpen(false);return <header className={'navigation '+(open?'expanded':'')}><div className="nav-bar"><button className="menu-toggle" aria-label={open?'Close menu':'Toggle menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'×':<span>☰</span>}</button><a href="#top" aria-label="StyleIQ home" onClick={close}><span className="wordmark">StyleIQ</span></a><a className="download" href={DOWNLOAD} onClick={close}>Get the app</a></div>{open&&<div className="menu-panel"><div className="menu-actions"><a href="#app-tour" onClick={close}>Explore StyleIQ ↗</a><a href={DOWNLOAD} onClick={close}>Get the app ↗</a></div><div className="menu-columns"><nav>{[['How it works','#how-it-works'],['Our story','#about'],['App tour','#app-tour'],['Get the app',DOWNLOAD]].map(([label,url])=><a key={label} href={url} onClick={close}>{label}<span>↗</span></a>)}</nav><div className="menu-contact"><p>Your wardrobe, thoughtfully styled.</p><p>Meet Olivia, your AI stylist. Explore outfit ideas, make your own looks and plan what comes next.</p><Socials/></div></div></div>}</header>}
export function Socials(){return <div className="socials"><a href="#how-it-works">How it works ↗</a><a href="#app-tour">Explore StyleIQ ↗</a></div>}
export function Footer(){return <footer id="get-the-app" className="site-footer"><div className="footer-top"><div className="contact-card"><h2>Your next favourite outfit could already be in your closet.</h2><p>Bring it together with StyleIQ. Discover outfit ideas, plan your looks, and make more of the pieces you own.</p><a className="pill" href="#app-tour">Explore the app ↗</a><p className="download-status">Download links coming soon.</p></div><Img className="team-polaroid" src="/assets/styleiq/man.webp" alt="Man wearing a navy blazer in a clothing studio"/></div><div className="footer-wordmark"><span className="wordmark">StyleIQ</span></div><div className="footer-bottom"><Socials/><span>© 2026 StyleIQ</span></div></footer>}
